from html import escape
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch

def generate_pdf_report(filename, target, scan_results, recommendations=None, hosts=None):
    document = SimpleDocTemplate(filename, pagesize=A4, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    story=[Paragraph("CyberScope — Network Scan Report", styles["Title"]), Spacer(1,0.15*inch),
           Paragraph(f"<b>Target:</b> {escape(str(target))}", styles["Normal"]), Spacer(1,0.12*inch)]
    if hosts:
        for host in hosts:
            story.append(Paragraph(f"<b>Host:</b> {escape(str(host.get('address','Unknown')))} | <b>State:</b> {escape(str(host.get('state','unknown')))} | <b>OS:</b> {escape(str(host.get('os','Not detected')))}", styles["Normal"]))
    story.append(Spacer(1,0.15*inch)); story.append(Paragraph("Port & Service Results", styles["Heading2"])); story.append(Spacer(1,0.08*inch))
    data=[["Port","Protocol","State","Service","Version"]]
    for result in scan_results or []:
        service=result.get("name",result.get("service","Unknown"))
        version=" ".join(v for v in [result.get("product",""),result.get("version",""),result.get("extrainfo","")] if v).strip() or result.get("version","") or "Not reported"
        data.append([str(result.get("port","Unknown")),str(result.get("protocol","TCP")),str(result.get("state","unknown")),str(service),version])
    if len(data)==1: data.append(["-","-","-","No open services reported","-"])
    table=Table(data,repeatRows=1,colWidths=[45,55,55,105,210])
    table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#e9eef5")),("TEXTCOLOR",(0,0),(-1,0),colors.black),("GRID",(0,0),(-1,-1),0.5,colors.grey),("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),8),("VALIGN",(0,0),(-1,-1),"TOP"),("BOTTOMPADDING",(0,0),(-1,0),7)]))
    story.extend([table,Spacer(1,0.2*inch),Paragraph("Defensive Recommendations", styles["Heading2"]),Spacer(1,0.08*inch)])
    for recommendation in recommendations or []:
        message=recommendation.get("message","") if isinstance(recommendation,dict) else str(recommendation)
        if message: story.append(Paragraph(f"• {escape(message)}",styles["Normal"])); story.append(Spacer(1,0.06*inch))
    story.append(Spacer(1,0.2*inch)); story.append(Paragraph("Generated by CyberScope — Network Security Scanner",styles["Italic"]))
    document.build(story); return filename
